"""Add knowledge_article_views table for unique view tracking

Revision ID: 2dc7de557a1c
Revises: 20260204_m365_ext
Create Date: 2026-02-06 07:30:59.757188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc7de557a1c'
down_revision: Union[str, None] = '20260204_m365_ext'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_article_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['knowledge_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_article_views_article_user', 'knowledge_article_views', ['article_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_knowledge_article_views_id'), 'knowledge_article_views', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_article_views_id'), table_name='knowledge_article_views')
    op.drop_index('ix_knowledge_article_views_article_user', table_name='knowledge_article_views')
    op.drop_table('knowledge_article_views')
    # ### end Alembic commands ###
